# /bin/bash -l
source scripts/func/config.sh

TAG_NAME=${GITHUB_REF#refs/tags/}
VERSION=($(grep -oE $(get_regex_version) <<<"$TAG_NAME"))
VERSION_ENV=${VERSION[0]}
VERSION_MAJOR=${VERSION[1]}
VERSION_MINOR=${VERSION[2]}
VERSION_PATCHES=${VERSION[3]}
VERSION_BUILD_NUMBER=${VERSION[4]}
VERSION_FULL=${VERSION_MAJOR}.${VERSION_MINOR}.${VERSION_PATCHES}
VERSION_ENV_LABEL="Development"
# ===== CONFIGS BUILD FOR IOS
IOS_APP_SCHEME="LibertyApp"
IOS_APP_CONFIGURATION="Debug"

if [ $VERSION_ENV = "stg" ]; then
    VERSION_ENV_LABEL="Staging"
fi

if [ $VERSION_ENV = "pro" ]; then
    VERSION_ENV_LABEL="Production"
fi

echo "APP_BUILD_TAG=$VERSION_ENV" >> $GITHUB_ENV
echo "APP_BUILD_VERSION=$VERSION_FULL" >> $GITHUB_ENV
echo "APP_BUILD_NUMBER=$VERSION_BUILD_NUMBER" >> $GITHUB_ENV
echo "APP_BUILD_TAG_LABEL=$VERSION_ENV_LABEL" >> $GITHUB_ENV
echo "TAG_SOURCE=$TAG_NAME" >> $GITHUB_ENV